// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToolBox_MVC.Data;

#nullable disable

namespace ToolBox_MVC.Migrations.ToolBoxDb
{
    [DbContext(typeof(ToolBoxDbContext))]
    [Migration("20250602130951_removedADCredentialsFrmMfServer")]
    partial class removedADCredentialsFrmMfServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ADAccountADGroup", b =>
                {
                    b.Property<int>("AccountsID")
                        .HasColumnType("int");

                    b.Property<int>("GroupsID")
                        .HasColumnType("int");

                    b.HasKey("AccountsID", "GroupsID");

                    b.HasIndex("GroupsID");

                    b.ToTable("ADAccountADGroup");
                });

            modelBuilder.Entity("MFilesAccountMFilesGroup", b =>
                {
                    b.Property<int>("AccountsId")
                        .HasColumnType("int");

                    b.Property<int>("GroupsId")
                        .HasColumnType("int");

                    b.HasKey("AccountsId", "GroupsId");

                    b.HasIndex("GroupsId");

                    b.ToTable("MFilesAccountMFilesGroup");
                });

            modelBuilder.Entity("ToolBox_MVC.Areas.LicenseManager.Models.DBModels.HistoryOperation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<bool>("Automatic")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("ID");

                    b.HasIndex("AccountId");

                    b.ToTable("HistoryOperations");
                });

            modelBuilder.Entity("ToolBox_MVC.Areas.LicenseManager.Models.DBModels.MFilesAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ADAccountGUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("License")
                        .HasColumnType("int");

                    b.Property<bool>("Maintained")
                        .HasColumnType("bit");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<int>("ServerRole")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ADAccountGUID");

                    b.HasIndex("ServerId");

                    b.HasIndex("AccountName", "ServerId")
                        .IsUnique();

                    b.ToTable("MFilesAccounts");
                });

            modelBuilder.Entity("ToolBox_MVC.Areas.LicenseManager.Models.DBModels.MFilesGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ADGroupGUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MFilesId")
                        .HasColumnType("int");

                    b.Property<bool>("Maintained")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ADGroupGUID");

                    b.HasIndex("ServerId");

                    b.HasIndex("MFilesId", "ServerId")
                        .IsUnique()
                        .HasFilter("[ServerId] IS NOT NULL");

                    b.ToTable("MFilesGroups");
                });

            modelBuilder.Entity("ToolBox_MVC.Areas.LicenseManager.Models.DBModels.MFilesServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveDirectoryID")
                        .HasColumnType("int");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NetworkAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProtocolSequence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("SyncTime")
                        .HasColumnType("time");

                    b.Property<string>("VaultGuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveDirectoryID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MFilesServers");
                });

            modelBuilder.Entity("ToolBox_MVC.Models.ADAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ActiveDirectoryID")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("GUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ActiveDirectoryID");

                    b.ToTable("ADAccounts");
                });

            modelBuilder.Entity("ToolBox_MVC.Models.ADGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ActiveDirectoryID")
                        .HasColumnType("int");

                    b.Property<string>("GUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ActiveDirectoryID");

                    b.ToTable("ADGroups");
                });

            modelBuilder.Entity("ToolBox_MVC.Models.ActiveDirectory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContextType")
                        .HasColumnType("int");

                    b.Property<DateOnly>("LastSync")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ActiveDirectories");
                });

            modelBuilder.Entity("ADAccountADGroup", b =>
                {
                    b.HasOne("ToolBox_MVC.Models.ADAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToolBox_MVC.Models.ADGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MFilesAccountMFilesGroup", b =>
                {
                    b.HasOne("ToolBox_MVC.Areas.LicenseManager.Models.DBModels.MFilesAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToolBox_MVC.Areas.LicenseManager.Models.DBModels.MFilesGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToolBox_MVC.Areas.LicenseManager.Models.DBModels.HistoryOperation", b =>
                {
                    b.HasOne("ToolBox_MVC.Areas.LicenseManager.Models.DBModels.MFilesAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ToolBox_MVC.Areas.LicenseManager.Models.DBModels.MFilesAccount", b =>
                {
                    b.HasOne("ToolBox_MVC.Models.ADAccount", "ADAccount")
                        .WithMany()
                        .HasForeignKey("ADAccountGUID")
                        .HasPrincipalKey("GUID");

                    b.HasOne("ToolBox_MVC.Areas.LicenseManager.Models.DBModels.MFilesServer", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ADAccount");
                });

            modelBuilder.Entity("ToolBox_MVC.Areas.LicenseManager.Models.DBModels.MFilesGroup", b =>
                {
                    b.HasOne("ToolBox_MVC.Models.ADGroup", "ADGroup")
                        .WithMany()
                        .HasForeignKey("ADGroupGUID")
                        .HasPrincipalKey("GUID");

                    b.HasOne("ToolBox_MVC.Areas.LicenseManager.Models.DBModels.MFilesServer", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId");

                    b.Navigation("ADGroup");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("ToolBox_MVC.Areas.LicenseManager.Models.DBModels.MFilesServer", b =>
                {
                    b.HasOne("ToolBox_MVC.Models.ActiveDirectory", "ActiveDirectory")
                        .WithMany()
                        .HasForeignKey("ActiveDirectoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ToolBox_MVC.Areas.LicenseManager.Models.DBModels.AutomaticOperations", "AutomaticOP", b1 =>
                        {
                            b1.Property<int>("MFilesServerId")
                                .HasColumnType("int");

                            b1.Property<bool>("AutoActivationHandling")
                                .HasColumnType("bit");

                            b1.Property<bool>("AutoRemove")
                                .HasColumnType("bit");

                            b1.Property<bool>("AutoRestore")
                                .HasColumnType("bit");

                            b1.HasKey("MFilesServerId");

                            b1.ToTable("MFilesServers");

                            b1.WithOwner()
                                .HasForeignKey("MFilesServerId");
                        });

                    b.OwnsOne("ToolBox_MVC.Areas.LicenseManager.Models.DBModels.MFilesCredential", "MfCredential", b1 =>
                        {
                            b1.Property<int>("MFilesServerId")
                                .HasColumnType("int");

                            b1.Property<string>("EncryptedPassword")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("EncryptedUserName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MFilesServerId");

                            b1.ToTable("MFilesServers");

                            b1.WithOwner()
                                .HasForeignKey("MFilesServerId");
                        });

                    b.Navigation("ActiveDirectory");

                    b.Navigation("AutomaticOP")
                        .IsRequired();

                    b.Navigation("MfCredential")
                        .IsRequired();
                });

            modelBuilder.Entity("ToolBox_MVC.Models.ADAccount", b =>
                {
                    b.HasOne("ToolBox_MVC.Models.ActiveDirectory", "ActiveDirectory")
                        .WithMany()
                        .HasForeignKey("ActiveDirectoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveDirectory");
                });

            modelBuilder.Entity("ToolBox_MVC.Models.ADGroup", b =>
                {
                    b.HasOne("ToolBox_MVC.Models.ActiveDirectory", "ActiveDirectory")
                        .WithMany()
                        .HasForeignKey("ActiveDirectoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveDirectory");
                });

            modelBuilder.Entity("ToolBox_MVC.Models.ActiveDirectory", b =>
                {
                    b.OwnsOne("ToolBox_MVC.Models.Credentials", "EncryptedCredentials", b1 =>
                        {
                            b1.Property<int>("ActiveDirectoryID")
                                .HasColumnType("int");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ActiveDirectoryID");

                            b1.ToTable("ActiveDirectories");

                            b1.WithOwner()
                                .HasForeignKey("ActiveDirectoryID");
                        });

                    b.Navigation("EncryptedCredentials")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
