// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToolBox_MVC.Areas.LicenseManager.Data;

#nullable disable

namespace ToolBox_MVC.Migrations
{
    [DbContext(typeof(LicenseManagerDBContext))]
    partial class LicenseManagerDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ToolBox_MVC.Areas.LicenseManager.Models.DBModels.DBAccount", b =>
                {
                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Server")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LicenseType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MaintainedID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerRoles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountName", "Server");

                    b.ToTable("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
